#!/bin/sh

#Switches all links to linux32 one for a mixed kernel version system

#pkgname=

rm -f /usr/bin/pcan_make_devices
ln -s /usr/share/"$pkgname"/bin/pcan_make_devices /usr/bin/pcan_make_devices
rm -f /usr/bin/pcan_usb_minor_check
ln -s /usr/share/"$pkgname"/bin/pcan_usb_minor_check /usr/bin/pcan_usb_minor_check
rm -f /etc/udev/rules.d/45-pcan.rules
ln -s /usr/share/"$pkgname"/udev/45-pcan.rules /etc/udev/rules.d/45-pcan.rules
rm -f /etc/modprobe.d/blacklist-peak.conf
ln -s /usr/share/"$pkgname"/udev/blacklist-peak.conf /etc/modprobe.d/blacklist-peak.conf
rm -f /usr/include/pcan.h
ln -s /usr/share/"$pkgname"/include/pcan.h /usr/include/pcan.h
rm -f /usr/include/libpcan.h
ln -s /usr/share/"$pkgname"/include/libpcan.h /usr/include/libpcan.h


TARGET=libpcan.so.0.6
rm -f /usr/lib/libpcan*
ln -s $sharedir/lib/$TARGET /usr/lib/libpcan.so.0.6
ln -s $sharedir/lib/$TARGET /usr/lib/libpcan.so.0
ln -s $sharedir/lib/$TARGET /usr/lib/libpcan.so

rm -f /usr/bin/pcan-receivetest
rm -f /usr/bin/pcan-transmitest
rm -f /usr/bin/pcan-bitratetest
rm -f /usr/bin/pcan-filtertest
rm -f /usr/bin/pcan-settings

ln -s $sharedir/bin/pcan-receivetest /usr/bin/pcan-receivetest
ln -s $sharedir/bin/pcan-transmitest /usr/bin/pcan-transmitest
ln -s $sharedir/bin/pcan-bitratetest /usr/bin/pcan-bitratetest
ln -s $sharedir/bin/pcan-filtertest /usr/bin/pcan-filtertest
ln -s $sharedir/bin/pcan-settings /usr/bin/pcan-settings

